language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu xenial main universe multiverse restricted' -y
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.6-xenial -y
  - sudo apt-get update -qq
  
install:
  - sudo apt-get -y install x264 gstreamer1.0-* qt512x11extras qt512multimedia qt512tools qt512translations qt512svg qt512imageformats libx11-dev libgstreamer1.0-dev libgl1-mesa-dev imagemagick
  - source /opt/qt*/bin/qt*-env.sh
  
script:
  - cd src/
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - mogrify -resize 256x256 applications/vokoscreenNG.png # FIXME: Icon in the repo is non-standard size
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - cp applications/vokoscreenNG.png appdir/
  - wget -c -nv https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
  - chmod +x ./appimagetool-*.AppImage
  - mkdir -p appdir/usr/lib/x86_64-linux-gnu/gstreamer-1.0/ ; cp -r /usr/lib/x86_64-linux-gnu/gstreamer-1.0/* appdir/usr/lib/x86_64-linux-gnu/gstreamer-1.0/ # FIXME: Should go-appimage do this?
  - ./appimagetool-*.AppImage deploy appdir/usr/share/applications/*.desktop -s=true
  - ( cd appdir/usr/bin ;  ln -s ../../opt/qt512/plugins/* . ) # FIXME in go-appimage
  - rm appdir/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstclutter-3.0.so # FIXME in go-appimage
  - rm appdir/usr/lib/x86_64-linux-gnu/libva-x11.so.1 # FIXME in go-appimage
  - rm appdir/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so # FIXME in go-appimage
  - chmod +x appdir/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner # FIXME in go-appimage; why is this needed?
  - ./appimagetool-*.AppImage appdir/
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
