language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.6-xenial -y
  - sudo apt-get update -qq
  
install:
  - sudo apt-get -y install qt512x11extras qt512multimedia qt512tools qt512translations libx11-dev libgstreamer1.0-dev libgl1-mesa-dev imagemagick
  - source /opt/qt*/bin/qt*-env.sh
  
script:
  - cd src/
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - mogrify -resize 256x256 applications/vokoscreenNG.png # FIXME: Icon in the repo is non-standard size
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - cp applications/vokoscreenNG.png appdir/
  - wget -c -nv https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
  - chmod +x ./appimagetool-*.AppImage
  - ./appimagetool-*.AppImage deploy appdir/usr/share/applications/*.desktop
  - ./appimagetool-*.AppImage appdir/
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
